version: "3"

services:
  # Gateway sidecar: receives client HTTP, forwards to gateway
  envoy-gateway:
    build:
      context: ./sidecar
      args:
        - CONFIG_FILE=envoy-gateway.yaml
    ports:
      - "10000:10000"
      - "9901:9901"
    depends_on:
      - gateway
      - jaeger
  # Backend sidecar: receives gRPC from gateway, forwards to backend-grpc
  envoy-backend:
    build:
      context: ./sidecar
      args:
        - CONFIG_FILE=envoy-backend.yaml
    depends_on:
      - backend-grpc
      - jaeger
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=gateway
    environment:
      - BACKEND_ADDR=envoy-backend:10001
      - SAMPLING_RATIO=1
      - EXPORTER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
  backend-grpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=backend-grpc
    environment:
      - EXPORTER_ENDPOINT=http://jaeger:14268/api/traces
      - SAMPLING_RATIO=1
    depends_on:
      - jaeger
  jaeger:
    image: "jaegertracing/all-in-one:1.42"
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
